<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="0" failures="1" finished="true" name="Test Run: 54" tests="2" total_time="Finished in: 0.77 secs."/>
<test location="D:\python\requests1\test\test_request\request_case.py" status="ok" test="request_case.test_one" time="0.48">
<stdout><![CDATA[https://www.apiopen.top/createUser?key=00d91e8e0cca2b76f515926a36db68f5&&phone=1778158785&passwd=123456
{"code":202,"msg":"&#29992;&#25143;&#24050;&#27880;&#20876;&#65281;","data":null}
&#38142;&#25509;&#25104;&#21151;
close
]]></stdout>
<stderr/>
</test>
<test location="D:\python\requests1\test\test_request\request_case.py" status="fail" test="request_case.test_two" time="">
<stdout><![CDATA[{"code":202,"msg":"&#29992;&#25143;&#24050;&#27880;&#20876;&#65281;","data":null}
https://www.apiopen.top/createUser?key=00d91e8e0cca2b76f515926a36db68f5&&phone=18752582342&passwd=123654
close
]]></stdout>
<stderr><![CDATA[Traceback (most recent call last):
  File "D:\python\requests1\test\test_request\request_case.py", line 28, in test_two
    self.assertCountEqual(self.request1['msg'], '&#25104;&#21151;!')
AssertionError: Element counts were not equal:
First has 1, Second has 0:  '&#29992;'
First has 1, Second has 0:  '&#25143;'
First has 1, Second has 0:  '&#24050;'
First has 1, Second has 0:  '&#27880;'
First has 1, Second has 0:  '&#20876;'
First has 1, Second has 0:  '&#65281;'
First has 0, Second has 1:  '&#25104;'
First has 0, Second has 1:  '&#21151;'
First has 0, Second has 1:  '!'
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="requests1 request_case.py"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
